import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import HeaderBottom from "@/components/common/HeaderBottom";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};
const menus = [
  {
    name: "Today Deals",
  },
  {
    name: "Ecommerce miniTV",
  },
  {
    name: "Best Sellers",
  },
  {
    name: "Mobiles",
  },
  {
    name: "Customer Service",
  },
  {
    name: "Electronics",
  },
  {
    name: "New Release",
  },
  {
    name: "Home & Kitchen",
  },
  {
    name: "Fashion",
  },
  {
    name: "Ecommerce Pay",
  },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <HeaderBottom menus={menus} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
